{% set version = "0.20.0" %}
{% set python_min = "3.7" %}

package:
  name: movingpandas
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/movingpandas/movingpandas-{{ version }}.tar.gz
  sha256: 9695e70ac46799f347dcc5c95a23c1d2efcee4cfb2b86d0c5e9766163c27e2d3

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - geopandas-base
    - geopy
    - matplotlib-base
    - pyproj

test:
  requires:
    - python {{ python_min }}
  imports:
    - movingpandas

about:
  home: https://github.com/movingpandas/movingpandas
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'MovingPandas provides trajectory data structures and functions for handling movement data'

extra:
  recipe-maintainers:
    - raybellwaves
    - anitagraser
    - jorisvandenbossche
