{% set version = "0.17.1" %}

package:
  name: movingpandas
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/movingpandas/movingpandas-{{ version }}.tar.gz
  sha256: 1789aecf24bc7611ea5364a56d829c94e4b37d7d45d64840dd4deb24fdef2b6f

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - fiona
    - geopandas-base
    - geopy
    - matplotlib-base
    - rtree

test:
  imports:
    - movingpandas

about:
  home: https://github.com/movingpandas/movingpandas
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'MovingPandas implements Trajectory classes and corresponding methods based on GeoPandas'

extra:
  recipe-maintainers:
    - raybellwaves
    - anitagraser
    - jorisvandenbossche
