{% set version = "0.18.0" %}

package:
  name: movingpandas
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/movingpandas/movingpandas-{{ version }}.tar.gz
  sha256: 279a22f6c5d85ec301769c1206688574069e8477913f3a54265418f4866d9159

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - fiona
    - geopandas-base
    - geopy
    - matplotlib-base
    - rtree

test:
  imports:
    - movingpandas

about:
  home: https://github.com/movingpandas/movingpandas
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'MovingPandas implements Trajectory classes and corresponding methods based on GeoPandas'

extra:
  recipe-maintainers:
    - raybellwaves
    - anitagraser
    - jorisvandenbossche
