{% set version = "0.17.2" %}

package:
  name: movingpandas
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/movingpandas/movingpandas-{{ version }}.tar.gz
  sha256: a84bab2473a0ee254ac10bd562b4c4c955ea69820a033be0220abd4cd2476c6e

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - fiona
    - geopandas-base
    - geopy
    - matplotlib-base
    - rtree

test:
  imports:
    - movingpandas

about:
  home: https://github.com/movingpandas/movingpandas
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'MovingPandas implements Trajectory classes and corresponding methods based on GeoPandas'

extra:
  recipe-maintainers:
    - raybellwaves
    - anitagraser
    - jorisvandenbossche
